#!/usr/bin/env zsh

# Mac
# ---
log_begin "docker"

if [[ "$OS_TYPE" == "mac" ]]; then
  if [ -z "$(command -v 'docker')" ]; then
    arch_string="$ARCH_TYPE"
    if [[ "$ARCH_TYPE" != "arm64" ]]; then
      arch_string="amd64"
    fi

    curl -o "$HOME/Downloads/Docker.dmg" "https://desktop.docker.com/mac/main/$arch_string/Docker.dmg"
    echo "Make sure to install Docker yourself: $HOME/Downloads/Docker.dmg"
    open "$HOME/Downloads"
  fi
elif [[ "$OS_TYPE" == "debian" ]]; then
  if [ -z "$(command -v 'docker')" ]; then

    sudo apt install docker.io -y

    # # Install
    # sudo apt-get update
    # sudo apt-get install ca-certificates curl
    # sudo install -m 0755 -d /etc/apt/keyrings
    # sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
    # sudo chmod a+r /etc/apt/keyrings/docker.asc

    # # Add the repository to Apt sources:
    # echo \
    #   "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
    #   $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
    #   sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    # sudo apt-get update

    # sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

    # # Enable docker
    # sudo systemctl enable docker.service
    # sudo systemctl enable containerd.service
    # sudo groupadd docker
    # sudo usermod -aG docker "$USER"
    # newgrp docker
  fi
else
  echo "'docker' install not supported by OS."
fi

log_end "docker"