#!/usr/bin/env zsh

bin_path="openjdk/bin"

if [[ "$OS_TYPE" == "mac" ]]; then
  expect_truthy "$(echo $PATH | grep $bin_path)" "$bin_path"
else
  expect_falsy "$(echo $PATH | grep $bin_path)" "$bin_path"
fi
