#!/usr/bin/env zsh

setup_rc() {
  # This path is set in .local/nvim/scripts/setup/lsp.sh
  local path_luamake="$PROJECTS_PATH/lsp/lua-language-server/3rd/luamake/luamake"

  if [ -e $path_luamake ]; then
    alias luamake=$path_luamake
  fi
}

setup_rc