#!/usr/bin/env zsh

if [[ -z "$(command -v 'tmux')" ]]; then
  log_begin "tmux"

  if [[ "$OS_TYPE" == "mac" ]]; then
    brew install tmux
  elif [[ "$OS_TYPE" == "debian" ]]; then
    if [ -n "$PROJECTS_PATH" ]; then
      sudo apt install libevent-dev # Install deps

      git clone https://github.com/tmux/tmux.git "$PROJECTS_PATH/tmux"
      cd "$PROJECTS_PATH/tmux"
      git tag --list | tail -n 1 | xargs git checkout # Checkout to latest tag
      sh autogen.sh
      ./configure && make

      mv "$PROJECTS_PATH/tmux/tmux" "$XDG_BIN_HOME"
    else
      sudo apt install tmux
    fi
  else
    echo "'tmux' install not supported by OS."
  fi

  log_end "tmux"
fi