#!/usr/bin/env zsh

if [[ $IS_MAC == 1 ]]; then
  if [ -z $(command -v "brew") ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  brew update
fi
