#!/usr/bin/env zsh

if [[ "$OS_TYPE" == "mac" ]]; then
  if [ -z $(command -v "brew") ]; then
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  brew update
fi