#!/usr/bin/env zsh

# These apps are installed in a typical and common way so it's easier to
# group them than to have seperate directories for each app

# GUI apps
# --------

# "<homebrew install name>|<flatpak install name>" separated by pipe
# Anything added here should provide both the hombrew and flatpak
# install name
gui_apps_to_install=(
  "alfred|"
  "bitwarden|com.bitwarden.desktop"
  "discord|discordapp"
  "ferdium|org.ferdium.Ferdium"
  "firefox|org.mozilla.firefox"
  "google-chrome|com.google.Chrome"
  "signal|org.signal.Signal"
  "slack|com.slack.Slack"
  "steam|com.valvesoftware.Steam"
  "sublime-merge|com.sublimemerge.App"
  "sublime-text|com.sublimetext.three"
  "telegram|org.telegram.desktop"
  "visual-studio-code|com.visualstudio.code"
  "vlc|org.videolan.VLC"
  "|com.github.tchx84.Flatseal"
  "|io.github.Hexchat"
  "|io.github.seadve.Kooha"
  "|com.usebottles.bottles"
  "obsidian|md.obsidian.Obsidian"
)
for i in "${gui_apps_to_install[@]}"; do
  mac_app_name=${i%\|*}
  linux_app_name=${i#*\|}

  if [[ "$OS_TYPE" == "mac" ]]; then
    if [ -n $mac_app_name ]; then
      log_begin "$mac_app_name"

      brew install --cask "$mac_app_name"

      log_end "$mac_app_name"
    fi
  else
    if [[ -n $linux_app_name && -z "$(flatpak list --app | grep $linux_app_name)" ]]; then
      log_begin "$linux_app_name"

      flatpak install --noninteractive "$linux_app_name"

      log_end "$linux_app_name"
    fi
  fi
done

if [[ $OS_TYPE == "debian" ]]; then
  # Permission setup
  # ----------------
  # start sublime-merge
  rmdir $HOME/.var/app/com.sublimemerge.App/config/git
  ln -s "$DOTFILES_REPO_PATH/.config/git" $HOME/.var/app/com.sublimemerge.App/config/git
  # end sublime-merge
fi

unset mac_app_name linux_app_name