#!/usr/bin/env zsh

if [[ "$OS_TYPE" == "debian" ]]; then
  log_begin "polychromatic"

  # First install OpenRazer (backend)
  sudo apt install software-properties-gtk
  sudo add-apt-repository ppa:openrazer/stable
  sudo apt update
  sudo apt install openrazer-meta

  # Then Polychromatic (frontend)
  sudo add-apt-repository ppa:polychromatic/stable
  sudo apt update

  # Full installation
  sudo apt install polychromatic

  log_end "polychromatic"
fi