#!/usr/bin/env zsh

export BASE16_THEME_DEFAULT="ocean"
export BASE16_HEXCHAT_COLORS_CONF_PATH="$HOME/.var/app/io.github.Hexchat/config/hexchat/colors.conf"
export BASE16_HEXCHAT_PATH="$PROJECTS_PATH/tinted-theming/base16-hexchat"
export BASE16_SHELL_ENABLE_VARS="1"
export BASE16_SHELL_PATH="$PROJECTS_PATH"/tinted-theming/base16-shell
export BASE16_TMUX_OPTION_ACTIVE="1"
export BASE16_TMUX_OPTION_STATUSBAR="1"

if [[ "$OS_TYPE" == "mac" ]]; then
  export BASE16_SHELL_SUBLIMEMERGE_PACKAGE_PATH="$HOME/Library/Application Support/Sublime Merge/Packages"
else
  export BASE16_SHELL_SUBLIMEMERGE_PACKAGE_PATH="$HOME/.var/app/com.sublimemerge.App/config/sublime-merge/Packages"
fi