#!/usr/bin/env zsh

setup_rc() {
  local fzf_ansi_script="$PROJECTS_PATH/tinted-theming/tinted-fzf/ansi/ansi.sh";
  if [ -f "$fzf_ansi_script" ]; then
    . "$fzf_ansi_script"
  fi

  tinty init
}

setup_rc