#!/usr/bin/env zsh

# This should be updated with each terminal session so it's here and not
# in an exports file
export GOROOT_BOOTSTRAP="$GOROOT"

setup_rc() {
  local gvm_script_path="$HOME/.gvm/scripts/gvm"

  if [ -s $gvm_script_path ]; then
    . "$gvm_script_path"
  fi
}

setup_rc