return {}
-- return {
--   "ellisonleao/gruvbox.nvim",
--   config = function()
-- -- require("gruvbox").setup({
-- --     palette_overrides = {
-- --         bright_green = "#990000",
-- --     }
-- -- })
-- vim.cmd("colorscheme gruvbox")
--   end
-- }