#!/usr/bin/env zsh

# If flatpak doesn't exist, install it

if [[ "$OS_TYPE" == "debian" && -z "$(command -v 'flatpak')"  ]]; then
  log_begin "flatpak"

  sudo apt install flatpak
  flatpak remote-add --if-not-exists flathub https://dl.flathub.org/repo/flathub.flatpakrepo

  log_end "flatpak"
else
  echo "flatbak not supported by OS."
fi