#!/usr/bin/env zsh

# If flatpak doesn't exist, install it
if [[ "$OS_TYPE" == "debian" ]]; then
  if [ -z $(command -v "flatpak") ]; then
    sudo apt install flatpak
  fi
else
  echo "flatbak install not supported by OS."
fi