#!/usr/bin/env zsh

if [[ -z "$(command -v 'rename')" ]]; then
  log_begin "rename"

  if [[ "$OS_TYPE" == "mac" ]]; then
    brew install rename
  elif [[ "$OS_TYPE" == "debian" ]]; then
    sudo apt install rename
  else
    echo "'rename' install not supported by OS."
  fi

  log_end "rename"
fi