require("jamygolden/config/setup")
require("jamygolden/config/options")
require("jamygolden/config/keymaps")
require("jamygolden/config/autocmds")
require("jamygolden/config/colorscheme")
require("jamygolden/config/lazy")