#!/usr/bin/env zsh

bin_path="opt/gradle/gradle-7.5/bin"

if [[ $IS_MAC == 0 ]]; then
  expect_truthy "$(echo $PATH | grep $bin_path)" "$bin_path"
else
  expect_truthy "$(echo $PATH | grep -v $bin_path)" "$bin_path inverse"
fi

expect_exists "$(command -v 'gradle')" "gradle"
