#!/usr/bin/env zsh

# NVM: https://github.com/nvm-sh/nvm
#
setup_rc() {
  [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
}

setup_rc