#!/usr/bin/env zsh

# NVM: https://github.com/nvm-sh/nvm

[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

if [ -n "$BASH_VERSION" ]; then
  # This loads nvm bash_completion
  [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
fi

if [ -n "$ZSH_VERSION" ]; then
  # This loads nvm zsh_completion
  [ -s "$NVM_DIR/zsh_completion" ] && \. "$NVM_DIR/zsh_completion"
fi

