#!/usr/bin/env zsh

if [ -z "$(command -v 'trash-put')" ]; then
  log_begin "trash-cli"

  if [[ "$OS_TYPE" == "mac" ]]; then
    brew install trash-cli
  elif [[ "$OS_TYPE" == "debian" ]]; then
    sudo apt install trash-cli
  else
    echo "'trash-cli' install not supported by OS."
  fi

  log_end "trash-cli"
fi