#!/usr/bin/env zsh

setup_rc() {
  local original_cmd="rm"
  local new_cmd="trash-put"
  local new_cmd_path=$(command -v "$new_cmd")

  if [[ -n "$new_cmd_path" && "$new_cmd_path" != "$new_cmd" ]]; then
    alias $original_cmd=$new_cmd
  fi
}

setup_rc