#!/usr/bin/env zsh

if [[ -z "$(command -v 'direnv')" ]]; then
  log_begin "direnv"

  if [[ "$OS_TYPE" == "mac" ]]; then
    brew install direnv
  elif [[ "$OS_TYPE" == "debian" ]]; then
    sudo apt install direnv
  else
    echo "'direnv' install not supported by OS."
  fi

  log_end "direnv"
fi