#!/usr/bin/env zsh

if [[ "$OS_TYPE" == "mac" ]]; then
  brew install nvim
else
  install_path="$HOME/.local/bin/nvim"

  if [ -z "$install_path" ]; then
  	curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim.appimage
    chmod u+x ./nvim.appimage
    mv ./nvim.appimage $install_path
  fi

  unset install_path
fi