#!/usr/bin/env zsh

alias g="git"

if [[ "$OS_TYPE" == "debian" ]]; then
  # https://docs.github.com/en/authentication/managing-commit-signature-verification/telling-git-about-your-signing-key
  export GPG_TTY=$(tty)
fi