#!/usr/bin/env zsh

log_begin "intellij-idea"

if [[ "$OS_TYPE" == "mac" ]]; then
  brew install intellij-idea
elif [[ "$OS_TYPE" == "debian" ]]; then
  applications_path="$HOME/Applications"
  tmp_filename="jetbrains-toolbox.tar.gz"
  jetbrains_product_code="TBA"

  if [ ! -f "$applications_path/jetbrains-toolbox" ]; then
    curl -L "https://download.jetbrains.com/product?code=$jetbrains_product_code&latest&distribution=linux" --output $tmp_filename

    mkdir -p $applications_path
    tar -xvzf $tmp_filename -C $applications_path --strip 1
    rm $tmp_filename
  fi

  unset applications_path jetbrains_product_code
else
  echo "'intellij-idea' install not supported by OS."
fi

log_end "intellij-idea"