#!/usr/bin/env zsh

if [[ -z "$(command -v 'go')" && ! -f "$HOME/.gvm/scripts/gvm" ]]; then
  log_begin "Go"

  gvm install go1.4 -B
  gvm use go.14
  export GOROOT_BOOTSTRAP=$GOROOT
  gvm install go1.20.5

  log_end "Go"
fi