#!/usr/bin/env zsh

export GOPATH="$XDG_DATA_HOME/go"

if [[ "$OS_TYPE" == "mac" ]]; then
  expect_truthy "$(echo $PATH | grep -v 'go/bin')" "go/bin inverse"
else
  expect_truthy $(echo $PATH | grep 'go/bin') "go/bin"
fi

expect_exists "$(command -v 'go')" "go"