#!/usr/bin/env zsh

setup_rc() {
  local original_cmd="cat"
  local new_cmd="bat"
  local new_cmd_path=$(command -v "$new_cmd")

  if [[ -n "$new_cmd_path" && "$new_cmd_path" != "$new_cmd" ]]; then
    alias $original_cmd="$new_cmd --theme='base16-256'"
  fi
}

setup_rc