#!/usr/bin/env zsh

# https://github.com/ajeetdsouza/zoxide

if [ -s "$XDG_DATA_HOME/cargo/bin/zoxide" ]; then
  eval "$(zoxide init zsh)"
fi

# `z` is different to above since `zoxide` is the app and `z` is the
# command
if [[ -n "$(command -v 'zoxide')" && -n "$(command -v 'z')" ]]; then
  alias cd=z
fi