#!/usr/bin/env zsh

# FNM: https://github.com/Schniz/fnm
# An nvm replacement
setup_rc() {
  local fnm_dir="$XDG_DATA_HOME/fnm"
  if [ "$(command -v 'fnm')" ]; then
    eval "$(fnm env --use-on-cd --shell=zsh --fnm-dir=$fnm_dir)"
    # fmm completions --shell zsh
  fi
}

setup_rc