
[font]
size = 16.0

[font.bold]
family = "FiraMono Nerd Font"
style = "Bold"

[font.italic]
family = "FiraMono Nerd Font"
style = "Italic"

[font.normal]
family = "FiraMono Nerd Font"
style = "Medium"

[general]
import = ["~/.config/alacritty/colors.toml"]
