#!/usr/bin/env zsh

if [[ $IS_MAC == 1 ]]; then
  brew install alacritty
else
  # https://github.com/alacritty/alacritty/blob/master/INSTALL.md#debianubuntu
  sudo apt install cmake pkg-config libfreetype6-dev libfontconfig1-dev libxcb-xfixes0-dev libxkbcommon-dev python3
  cargo install alacritty

  # setup to install debian app icon
  install_path="$HOME/tmp-alacritty"
  git clone https://github.com/alacritty/alacritty.git $install_path
  cd $install_path

  # execution
  sudo tic -xe alacritty,alacritty-direct extra/alacritty.info
  sudo cp "$XDG_DATA_HOME"/cargo/bin/alacritty /usr/local/bin # or anywhere else in $PATH
  sudo cp extra/logo/alacritty-term.svg /usr/share/pixmaps/Alacritty.svg
  sudo desktop-file-install extra/linux/Alacritty.desktop
  sudo update-desktop-database

  # cleanup
  cd -
  rm -r $install_path
fi
