#!/usr/bin/env zsh

if [[ $IS_MAC == 1 ]]; then
  brew install alacritty
else
  # Install through system to avoid permission issues
  sudo add-apt-repository -y ppa:mmstick76/alacritty
  sudo apt install -y alacritty
fi
