#!/usr/bin/env zsh

# Mac
# ---

if [[ $IS_MAC == 1 ]]; then
  if [ -z $(command -v "docker") ]; then
    curl -o "$HOME/Downloads/Docker.dmg" "https://desktop.docker.com/mac/main/arm64/Docker.dmg?utm_source=docker&utm_medium=webreferral&utm_campaign=docs-driven-download-mac-arm64"
    echo "Make sure to install Docker yourself: $HOME/Downloads/Docker.dmg"
    open "$HOME/Downloads"
  fi
else
  if [ -z $(command -v "docker") ]; then
    sudo apt install -y apt-transport-https ca-certificates curl gnupg lsb-release
    sudo mkdir -m 0755 -p /etc/apt/keyrings
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    echo \
      "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
      $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
    # sudo chmod a+r /etc/apt/keyrings/docker.gpg
    sudo apt update # Above line may be required if update gives GPG error
    sudo apt -y install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
    systemctl enable docker.service
    systemctl enable containerd.service
    sudo systemctl enable docker.service
    sudo systemctl enable containerd.service
    sudo groupadd docker
  fi
fi
