#!/usr/bin/env zsh

# https://www.docker.com/

# Docker Desktop App
# ------------------
if [[ "$OS_TYPE" == "mac" ]]; then
  [ -s "$HOME/.docker/init-zsh.sh" ] && \. "$HOME/.docker/init-zsh.sh" || true
fi
